name: Build editor.js

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build with Webpack
        run: npx webpack --config BuilderFiles/webpack.config.js

      - name: Upload editor.js
        uses: actions/upload-artifact@v4
        with:
          name: editor-build
          path: dist/*.js
